version: '2'
services:

# zookeeper stores metadata or the kafka cluster nodes
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - 22181:2181

# kafka_broker provides: topics, partitions for producers and consumers
  kafka_broker:
    image: confluentinc/cp-kafka:5.2.4
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# promtail consumes messages from a kafka topic and remote writes them to Grafana Logs
  promtail:
    image: grafana/promtail:latest
    depends_on:
      - kafka_broker
    deploy:
      replicas: 2
    restart: always
    volumes:
      - type: bind
        source: ./promtail-config.yml
        target: /etc/promtail/promtail-config.yml
      - /var/log:/var/logtest:ro
    entrypoint:
      - /usr/bin/promtail
      - -config.expand-env=true
      - -config.file=/etc/promtail/promtail-config.yml
    environment:
      V1: 123
      V2: 567

# kafka_producer produces messages to a kafka topic
  producer:
    image: kafka_producer
    depends_on:
      - kafka_broker
    restart: always
    volumes:
      - type: bind
        source: ./kafka
        target: /home/test/kafka
      - type: bind
        source: ./kafka/producer.py
        target: /home/test/kafka/producer.py
    entrypoint:
      - python3
      - /home/test/kafka/producer.py
      - producerThreaded
    environment:
      KAFKA_BROKER: "kafka_broker:9092"
      KAFKA_TOPIC: "grafana"
      KAFKA_PRODUCER_INTERVAL: 15

# configurators creates the kafka topic
  configurator:
    image: kafka_producer
    depends_on:
      - kafka_broker
    volumes:
      - type: bind
        source: ./kafka
        target: /home/test/kafka
    entrypoint:
      - python3
      - /home/test/kafka/producer.py
      - createTopics
      - "300"
    environment:
      KAFKA_BROKER: "kafka_broker:9092"
      KAFKA_TOPIC: "grafana"
      KAFKA_PRODUCER_INTERVAL: 15

networks:
  kafka_network:
    name: kafka_docker_example_net
